# Generated by Django 3.2.7 on 2021-10-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0002_auto_20211006_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busgateinfo',
            name='citys',
        ),
    ]
