# Generated by Django 3.2.7 on 2021-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0003_remove_busgateinfo_citys'),
    ]

    operations = [
        migrations.AddField(
            model_name='busgateinfo',
            name='citys',
            field=models.ManyToManyField(to='Gate.Citys'),
        ),
        migrations.AlterField(
            model_name='citys',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
