# Generated by Django 3.2.7 on 2021-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0004_auto_20211006_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
