# Generated by Django 3.2.7 on 2021-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0006_locations_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='citys',
            name='loc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
