# Generated by Django 3.2.7 on 2021-10-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0007_citys_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='cty', to='Gate.busgateinfo'),
        ),
    ]
