# Generated by Django 3.2.7 on 2021-10-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gate', '0008_alter_locations_gate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citys',
            name='loc',
        ),
    ]
